name: destini_challenge_starting
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio_cache: ^0.1.2
  rflutter_alert: ^2.0.7
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  loading_animation_widget: ^1.2.1
  http: ^1.2.1
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - images/background.png
    - images/weather/city_background.jpg
    - images/weather/location_background.jpg

  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900